"use client";

import { useI18n } from "@/i18n/LanguageProvider";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from "docx";
import { saveAs } from "file-saver";

// Report output uses English labels only (no Chinese)
const REPORT_LABELS = {
  reportTitle: "AI Detection Report",
  brandLine: "StudyDone - AI Detector for Students & Teachers",
  wePredict: "We predict this text is",
  humanGenerated: "Human Generated",
  aiGenerated: "AI Generated",
  aiProbability: "AI Probability",
  aiProbabilityNote:
    "This number is the probability that the document is AI generated, not a percentage of AI text in the document.",
  plagiarism: "Plagiarism",
  plagiarismNotRun:
    "The plagiarism scan was not run for this document. Go to studydone.vip to check for plagiarism.",
  plagiarismRun: "Plagiarism scan was run for this document. See details below.",
  bibliographyTitle: "Bibliography / Plagiarism Scan",
  segmentsTitle: "Paragraph Risk Analysis",
  paragraphLabel: "Paragraph",
  explanationLabel: "Explanation",
  riskLow: "Low",
  riskMedium: "Medium",
  riskHigh: "High",
  footerNote: "Report generated by StudyDone — studydone.vip",
} as const;

// Font for runs that may contain Chinese (avoids garbled text in Word)
const DOC_FONT_CJK = {
  ascii: "Calibri",
  hAnsi: "Calibri",
  eastAsia: "SimSun",
} as const;

type Segment = {
  text: string;
  aiProbability: number;
  riskLevel: string;
  explanation: string;
};

type Props = {
  report: {
    id: string;
    fileName: string;
    overallScore: number;
    segments: Segment[];
    bibliographyScan?: Record<string, unknown> | null;
    createdAt?: string;
  };
  onBack: () => void;
};

export function ReportView({ report, onBack }: Props) {
  const { t } = useI18n();

  const scoreColor =
    report.overallScore < 40
      ? "text-green-600 dark:text-green-400"
      : report.overallScore < 70
        ? "text-amber-600 dark:text-amber-400"
        : "text-red-600 dark:text-red-400";

  const riskLabel = (level: string) => {
    if (level === "low") return REPORT_LABELS.riskLow;
    if (level === "medium") return REPORT_LABELS.riskMedium;
    return REPORT_LABELS.riskHigh;
  };

  const riskBadge = (level: string) => {
    const styles =
      level === "low"
        ? "bg-green-100 text-green-800 dark:bg-green-900/50 dark:text-green-400"
        : level === "medium"
          ? "bg-amber-100 text-amber-800 dark:bg-amber-900/50 dark:text-amber-400"
          : "bg-red-100 text-red-800 dark:bg-red-900/50 dark:text-red-400";
    return (
      <span className={`rounded-full px-3 py-1 text-xs font-medium ${styles}`}>
        {riskLabel(level)}
      </span>
    );
  };

  const handleDownloadPdf = () => {
    window.print();
  };

  const handleDownloadDoc = async () => {
    const children: Paragraph[] = [];
    const detectionTimeDoc = report.createdAt
      ? new Date(report.createdAt).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })
      : new Date().toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" });
    const isHumanDoc = report.overallScore < 0.5;
    const hasPlagDoc = report.bibliographyScan != null && Object.keys(report.bibliographyScan).length > 0;

    children.push(
      new Paragraph({
        text: `${REPORT_LABELS.brandLine}  ·  ${detectionTimeDoc}`,
        alignment: AlignmentType.RIGHT,
        spacing: { after: 200 },
      }),
      new Paragraph({
        text: REPORT_LABELS.reportTitle,
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        spacing: { after: 400 },
      }),
      new Paragraph({ text: REPORT_LABELS.wePredict, spacing: { after: 100 } }),
      new Paragraph({
        children: [
          new TextRun({
            text: isHumanDoc ? REPORT_LABELS.humanGenerated : REPORT_LABELS.aiGenerated,
            bold: true,
          }),
        ],
        spacing: { after: 200 },
      }),
      new Paragraph({ text: REPORT_LABELS.aiProbability, spacing: { after: 100 } }),
      new Paragraph({
        children: [new TextRun({ text: `${Math.round(report.overallScore * 100)}%`, bold: true, size: 32 })],
        spacing: { after: 100 },
      }),
      new Paragraph({ text: REPORT_LABELS.aiProbabilityNote, spacing: { after: 400 } }),
      new Paragraph({ text: REPORT_LABELS.plagiarism, spacing: { after: 100 } }),
      new Paragraph({
        text: hasPlagDoc ? REPORT_LABELS.plagiarismRun : `?  ${REPORT_LABELS.plagiarismNotRun}`,
        spacing: { after: 400 },
      }),
    );

    if (report.bibliographyScan != null && Object.keys(report.bibliographyScan).length > 0) {
      children.push(
        new Paragraph({
          text: REPORT_LABELS.bibliographyTitle,
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 200, after: 200 },
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: JSON.stringify(report.bibliographyScan, null, 2),
              font: DOC_FONT_CJK,
            }),
          ],
          spacing: { after: 400 },
        }),
      );
    }

    children.push(
      new Paragraph({
        text: REPORT_LABELS.segmentsTitle,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 200, after: 200 },
      }),
    );

    report.segments.forEach((seg, i) => {
      children.push(
        new Paragraph({
          text: `${REPORT_LABELS.paragraphLabel} ${i + 1} — ${riskLabel(seg.riskLevel)} | AI ${Math.round(seg.aiProbability * 100)}%`,
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 240, after: 120 },
        }),
        new Paragraph({
          children: [
            new TextRun({ text: seg.text, font: DOC_FONT_CJK }),
          ],
          spacing: { after: 120 },
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: `${REPORT_LABELS.explanationLabel}: `,
              bold: true,
              font: DOC_FONT_CJK,
            }),
            new TextRun({ text: seg.explanation, font: DOC_FONT_CJK }),
          ],
          spacing: { after: 240 },
        }),
      );
    });

    children.push(
      new Paragraph({ text: "", spacing: { before: 400 } }),
      new Paragraph({
        text: REPORT_LABELS.footerNote,
        alignment: AlignmentType.CENTER,
        spacing: { after: 200 },
      }),
    );

    const doc = new Document({
      sections: [
        {
          properties: {},
          children,
        },
      ],
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, "report.docx");
  };

  const detectionTime = report.createdAt
    ? new Date(report.createdAt).toLocaleString("en-US", {
        dateStyle: "medium",
        timeStyle: "short",
      })
    : new Date().toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" });
  const isHumanGenerated = report.overallScore < 0.5;
  const hasPlagiarismScan = report.bibliographyScan != null && Object.keys(report.bibliographyScan).length > 0;

  return (
    <div className="report-print-wrapper">
      {/* Page header: brand + detection time; in print repeats on each page */}
      <div className="report-page-header">
        <div className="flex items-center gap-3">
          <span className="text-xs text-slate-500 dark:text-slate-400">
            {REPORT_LABELS.brandLine}
          </span>
        </div>
        <span className="text-xs text-slate-500 dark:text-slate-400">{detectionTime}</span>
      </div>

      <div className="space-y-8 report-print-container">
        <div className="flex flex-wrap items-center justify-between gap-4 print:hidden">
          <div className="flex items-center gap-2">
            <button
              onClick={onBack}
              className="flex items-center gap-2 text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white"
            >
              <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
              </svg>
              {t("report.back")}
            </button>
          </div>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleDownloadPdf}
              className="rounded-md border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 shadow-sm hover:bg-slate-50 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-100 dark:hover:bg-slate-700"
            >
              {t("report.downloadPdf")}
            </button>
            <button
              type="button"
              onClick={handleDownloadDoc}
              className="rounded-md border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 shadow-sm hover:bg-slate-50 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-100 dark:hover:bg-slate-700"
            >
              {t("report.downloadDoc")}
            </button>
          </div>
        </div>

        {/* Overall assessment — new structure */}
        <div className="rounded-2xl border border-slate-200 bg-white p-8 dark:border-slate-700 dark:bg-slate-800/50">
          <p className="mb-2 text-sm text-slate-600 dark:text-slate-400">
            {REPORT_LABELS.wePredict}
          </p>
          <p
            className={`mb-6 text-2xl font-bold ${
              isHumanGenerated ? "text-green-600 dark:text-green-400" : "text-red-600 dark:text-red-400"
            }`}
          >
            {isHumanGenerated ? REPORT_LABELS.humanGenerated : REPORT_LABELS.aiGenerated}
          </p>
          <p className="mb-1 text-sm font-medium text-slate-700 dark:text-slate-300">
            {REPORT_LABELS.aiProbability}
          </p>
          <p className={`mb-4 text-4xl font-bold ${scoreColor}`}>
            {Math.round(report.overallScore * 100)}%
          </p>
          <p className="mb-8 text-xs text-slate-500 dark:text-slate-400 max-w-xl">
            {REPORT_LABELS.aiProbabilityNote}
          </p>
          <div className="border-t border-slate-200 pt-6 dark:border-slate-600">
            <p className="mb-1 text-sm font-medium text-slate-700 dark:text-slate-300">
              {REPORT_LABELS.plagiarism}
            </p>
            {hasPlagiarismScan ? (
              <p className="text-sm text-slate-600 dark:text-slate-400">
                {REPORT_LABELS.plagiarismRun}
              </p>
            ) : (
              <>
                <p className="mb-2 text-2xl font-bold text-slate-400 dark:text-slate-500">?</p>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  {REPORT_LABELS.plagiarismNotRun}
                </p>
              </>
            )}
          </div>
        </div>

      {report.bibliographyScan != null && Object.keys(report.bibliographyScan).length > 0 && (
        <div className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-700 dark:bg-slate-800/50">
          <h2 className="mb-4 text-lg font-semibold text-slate-900 dark:text-white">
            {REPORT_LABELS.bibliographyTitle}
          </h2>
          <pre className="overflow-auto rounded-lg bg-slate-50 p-4 text-sm text-slate-800 dark:bg-slate-900 dark:text-slate-200">
            {JSON.stringify(report.bibliographyScan, null, 2)}
          </pre>
        </div>
      )}

      <div>
        <h2 className="mb-4 text-lg font-semibold text-slate-900 dark:text-white">
          {REPORT_LABELS.segmentsTitle}
        </h2>
        <div className="space-y-6">
          {report.segments.map((seg, i) => (
            <div
              key={i}
              className={`rounded-xl border p-6 ${
                seg.riskLevel === "high"
                  ? "border-red-200 bg-red-50/50 dark:border-red-900/50 dark:bg-red-900/20"
                  : seg.riskLevel === "medium"
                    ? "border-amber-200 bg-amber-50/30 dark:border-amber-900/50 dark:bg-amber-900/20"
                    : "border-slate-200 bg-slate-50/30 dark:border-slate-700 dark:bg-slate-800/30"
              }`}
            >
              <div className="mb-3 flex items-center justify-between">
                <span className="text-sm font-medium text-slate-500 dark:text-slate-400">
                  {REPORT_LABELS.paragraphLabel} {i + 1}
                </span>
                <div className="flex items-center gap-2">
                  {riskBadge(seg.riskLevel)}
                  <span
                    className={`text-sm font-semibold ${
                      seg.aiProbability >= 0.7
                        ? "text-red-600"
                        : seg.aiProbability >= 0.4
                          ? "text-amber-600"
                          : "text-green-600"
                    }`}
                  >
                    AI {Math.round(seg.aiProbability * 100)}%
                  </span>
                </div>
              </div>
              <p className="mb-4 text-slate-800 dark:text-slate-200 leading-relaxed">
                {seg.text}
              </p>
              <div className="rounded-lg bg-white/80 p-3 text-sm text-slate-600 dark:bg-slate-900/50 dark:text-slate-400">
                <span className="font-medium">{REPORT_LABELS.explanationLabel}: </span>
                {seg.explanation}
              </div>
            </div>
          ))}
        </div>
      </div>
      </div>

      {/* Page footer */}
      <div className="report-page-footer">
        <span className="text-xs text-slate-400 dark:text-slate-500">
          {REPORT_LABELS.footerNote}
        </span>
      </div>
    </div>
  );
}
